#!/bin/bash
set -e

tag='wsf32'
if ! docker images | grep -q $tag; then 
   echo "Buliding  test docker image"
   docker build . -t $tag
else 
  echo "Docker image: $tag exists" 
fi

docker run -it --rm -v $(echo "$PWD/../ansible"):/ansible $tag bash 