# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  config.vm.box = "generic/fedora29"
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: "dnf install git ansible -y"
  config.vm.synced_folder "../ansible", "/home/vagrant/ansible", type: "sshfs"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "2"
  end
end
