---
- hosts: localhost
  vars:
    work_file_name: "wor.yml"

  #################################################################
  #################################################################
  #################################################################

  tasks:
    - name: Get fedora version
      shell: rpm -E %fedora
      register: fv
    - set_fact: fedora_current={{ fv.stdout }}

    - name: Work task list
      ansible.builtin.debug:
        msg: START Testing

    - name: Install {{ fedora_current }} rpmfusion repo packages
      become: yes
      dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm

    - name: Install the 'multimedia' package group
      become: yes
      dnf:
        name: "@multimedia"
        state: present
        exclude: PackageKit-gstreamer-plugin
        install_weak_deps: false

    - name: Install the 'sound-and-video' package group
      become: yes
      dnf:
        name: "@sound-and-video"
        state: present

    - name: Install the 'bat' package
      become: yes
      dnf:
        name: bat
        state: present

    #####################################################################
    #####################################################################
    #####################################################################
    #####################################################################

    - name: "Include {{ work_file_name }} file if it exists"
      ansible.builtin.include_tasks:
        file: "{{ work_file_name }}"
      when: "work_file_name is file"

    ##############
    # This also works #
    ##############
    # - name: Include WORK task list in play
    #   ansible.builtin.include_tasks:
    #     file: "{{ item }}"
    #   with_first_found:
    #     - files:
    #         - wor.yml
    #       skip: True

    #####################################################################
    #####################################################################
    #####################################################################
    #####################################################################

    - name: Work task list
      ansible.builtin.debug:
        msg: END Testing
